version: "3.9"  # optional since v1.27.0
services:
  mon:
    hostname: mon
    image: citusdata/pg_auto_failover:demo
    environment:
      PGDATA: /tmp/pgaf
      PG_AUTOCTL_DEBUG: 1
    command: pg_autoctl create monitor --ssl-self-signed --auth trust --run
    expose:
      - 5432
  pg1:
    hostname: pg1
    image: citusdata/pg_auto_failover:demo
    environment:
      PGDATA: /tmp/pgaf
      PG_AUTOCTL_DEBUG: 1
    command: [
      "pg_autoctl", "create", "postgres",
      "--ssl-self-signed",
      "--auth", "trust",
      "--pg-hba-lan",
      "--username", "ad",
      "--dbname", "analytics",
      "--name", "pg1",
      "--monitor", "postgresql://autoctl_node@mon/pg_auto_failover",
      "--run"]
    expose:
      - 5432
  pg2:
    hostname: pg2
    image: citusdata/pg_auto_failover:demo
    environment:
      PGDATA: /tmp/pgaf
      PG_AUTOCTL_DEBUG: 1
    command: [
      "pg_autoctl", "create", "postgres",
      "--ssl-self-signed",
      "--auth", "trust",
      "--pg-hba-lan",
      "--username", "ad",
      "--dbname", "analytics",
      "--name", "pg2",
      "--monitor", "postgresql://autoctl_node@mon/pg_auto_failover",
      "--run"]
    expose:
      - 5432
  lb:
    hostname: lb
    image: edoburu/pgbouncer
    environment:
       - DB_HOST=pg1,pg2
       - AUTH_TYPE=trust
    ports:
      - "5432:5432"
    depends_on:
      - pg1
      - pg2
  app:
    hostname: app
    image: postgres:14.4
    # command: ["bash", "-c", "sleep 100000"]
    command: ["bash", "-c", "sleep 100000"]
    depends_on:
      - lb
    volumes:
      - $PWD:/work
